baseurl = "/"
title = "Russell Writes Code"
theme = "hugo-coder"
languagecode = "en-us"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
    author = "Russell Patterson"
    info = "Software Engineer / Tech Enthusiast / Ally"
    description = "Russell Patterson's personal website"
    keywords = "blog,developer,personal"
    avatarurl = "images/profile_picture.jpeg"

    favicon_32 = "/img/favicon-32x32.png"
    favicon_16 = "/img/favicon-16x16.png"

    footercontent = "Not a strong bowler."

    hidecredits = true
    hidecopyright = false

    rtl = false

    math = true
    since = "2008"

[permalinks]
  posts = "/:year/:month/:title/"

# Social links
[[params.social]]
    name = "Github"
    icon = "fab fa-github fa-2x"
    weight = 1
    url = "https://github.com/rwpcpe/"

# Menu links
[[menu.main]]
    name = "About Me"
    weight = 1
    url  = "/about/"
[[menu.main]]
    name = "Blog"
    weight = 2
    url = "/posts/"
[[menu.main]]
    name = "Things I Work On"
    weight = 3
    url = "/things-i-work-on/"
[[menu.main]]
    name = "Contact"
    weight = 4
    url = "/contact/"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "monokai"
    tabWidth = 4
